### ISSUE TITLE
Using the proposed framework for 2023 Thailand General Election Forecast

### ISSUE THREAD

**Issue by bkktimber** [seungwoo-stat/20th-PE-forecast#1]
I came across your fantastic work! I want to build a similar forecasting framework for the upcoming General Election in Thailand.

Currently, I'm gathering poll results from several public polls in Thailand. Unfortunately, all of them are available at the national level only. I would like to know your opinion if it's possible to do with the framework in your work.

Thank you.

**Comment by seungwoo-stat** [comment]
Thanks for reading our paper.

I believe that it would be possible to apply our model, even when there are only national level polls. In eq (3.5), remove $\xi_{p(k),t(k)}$. Also, instead of giving a restriction on $\delta_{T}^\text{swing} = (0.25, 0.25, 0.25, 0.25)^\top$ as in the paper (where $T$ is the election date), give $\delta_{T}^\text{swing}$ a reasonable prior, e.g., forecast from the fundamentals-based model.

Best of luck with your forecast!

**Comment by bkktimber** [comment]
Thank you so much for your reply!
